| Question / Paper | The Anatomy of a Large-Scale Hypertextual Web Search Engine | Attention Is All You Need | On the Refinement of DHTs | Deep Latent Mixture Model for Recommendation | A Relational Model of Data for Large Shared Data Banks | Chord: A Scalable Peer-to-Peer Lookup Protocol for Internet Applications | Deep Factorization Model for Robust Recommendation |
|------------------|-------------------------------------------------------------|---------------------------|--------------------------|----------------------------------------------|-------------------------------------------------------|-------------------------------------------------------------------------|----------------------------------------------------|
| **Is this paper worth reading?** | Yes | It is easier to read and includes clear images | The abstract presentation is unclear. Figures and references are confusing | Yes | The abstract structure is unclear, but the content is acceptable | Yes | Yes |
| **Is it a famous paper?** | Yes, it is considered a must-read | Yes | Unknown | No | Yes | Yes | Yes |
| **Abstract clarity** | The problem is clearly stated, but the methods and contributions are not clearly explained | The problem, methods, and contributions are clearly explained | The problem is clear. The methods are mentioned but not well detailed. The contributions are unclear | The problem and methods are clear, but the final sentences and contributions are unclear | The problem and methods are clear, but the contributions are not clearly stated | The problem and methods are clear. The contributions of each author are not clearly specified | The problem and method are described, but in a very general way. Contributions are not clearly detailed |
| **Number of citations (Google Scholar)** | Cited by 25,679 papers. Latest citations in 2025 | Cited by 208,217 papers | Not available | No citations found | Cited by 15,475 papers | Cited by 4,446 papers | No citations found |
| **Citations impact** | Very highly cited and influential | Extremely influential | Low or unclear impact | Low impact | Highly influential foundational work | Highly cited and influential | Low impact |
| **Recency** | Published in 1998; considered a classic in computer science | Published in 2017; still widely used | Not specified | Published in 2022 | Published in 1986; foundational work | Published in 2003 | Published in 2022 |
| **Additional notes** | — | Images are clear and helpful | Images and references are unclear | — | From 1986 to 2012 it had between 250 and 300 citations per year. After 2005, citations increased to around 450 per year. Currently, citations are decreasing but still above 350 | It reached a peak of around 400 citations per year, but its relevance is now decreasing | — |


